# Example Travis config. See the entire example: https://github.com/JonathanPorta/ci-build

language: objective-c
osx_image: xcode61
rvm:
- 2.1.2
install:
- sudo bash ./Scripts/Install.sh
script:
- sudo bash ./Scripts/build.sh
